# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'page_6.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1366, 786)
        MainWindow.setStyleSheet(u"background-color: rgb(170, 170, 255);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(990, 30, 351, 701))
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.btn_3 = QPushButton(self.centralwidget)
        self.btn_3.setObjectName(u"btn_3")
        self.btn_3.setGeometry(QRect(110, 200, 61, 61))
        font = QFont()
        font.setPointSize(21)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_2 = QPushButton(self.centralwidget)
        self.btn_2.setObjectName(u"btn_2")
        self.btn_2.setGeometry(QRect(110, 260, 61, 61))
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_1 = QPushButton(self.centralwidget)
        self.btn_1.setObjectName(u"btn_1")
        self.btn_1.setGeometry(QRect(110, 320, 61, 61))
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_6 = QPushButton(self.centralwidget)
        self.btn_6.setObjectName(u"btn_6")
        self.btn_6.setGeometry(QRect(170, 200, 61, 61))
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_5 = QPushButton(self.centralwidget)
        self.btn_5.setObjectName(u"btn_5")
        self.btn_5.setGeometry(QRect(170, 260, 61, 61))
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_4 = QPushButton(self.centralwidget)
        self.btn_4.setObjectName(u"btn_4")
        self.btn_4.setGeometry(QRect(170, 320, 61, 61))
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_9 = QPushButton(self.centralwidget)
        self.btn_9.setObjectName(u"btn_9")
        self.btn_9.setGeometry(QRect(230, 200, 61, 61))
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_8 = QPushButton(self.centralwidget)
        self.btn_8.setObjectName(u"btn_8")
        self.btn_8.setGeometry(QRect(230, 260, 61, 61))
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_7 = QPushButton(self.centralwidget)
        self.btn_7.setObjectName(u"btn_7")
        self.btn_7.setGeometry(QRect(230, 320, 61, 61))
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_12 = QPushButton(self.centralwidget)
        self.btn_12.setObjectName(u"btn_12")
        self.btn_12.setGeometry(QRect(290, 200, 61, 61))
        self.btn_12.setFont(font)
        self.btn_12.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_11 = QPushButton(self.centralwidget)
        self.btn_11.setObjectName(u"btn_11")
        self.btn_11.setGeometry(QRect(290, 260, 61, 61))
        self.btn_11.setFont(font)
        self.btn_11.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_10 = QPushButton(self.centralwidget)
        self.btn_10.setObjectName(u"btn_10")
        self.btn_10.setGeometry(QRect(290, 320, 61, 61))
        self.btn_10.setFont(font)
        self.btn_10.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_15 = QPushButton(self.centralwidget)
        self.btn_15.setObjectName(u"btn_15")
        self.btn_15.setGeometry(QRect(350, 200, 61, 61))
        self.btn_15.setFont(font)
        self.btn_15.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_14 = QPushButton(self.centralwidget)
        self.btn_14.setObjectName(u"btn_14")
        self.btn_14.setGeometry(QRect(350, 260, 61, 61))
        self.btn_14.setFont(font)
        self.btn_14.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_13 = QPushButton(self.centralwidget)
        self.btn_13.setObjectName(u"btn_13")
        self.btn_13.setGeometry(QRect(350, 320, 61, 61))
        self.btn_13.setFont(font)
        self.btn_13.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_18 = QPushButton(self.centralwidget)
        self.btn_18.setObjectName(u"btn_18")
        self.btn_18.setGeometry(QRect(410, 200, 61, 61))
        self.btn_18.setFont(font)
        self.btn_18.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_17 = QPushButton(self.centralwidget)
        self.btn_17.setObjectName(u"btn_17")
        self.btn_17.setGeometry(QRect(410, 260, 61, 61))
        self.btn_17.setFont(font)
        self.btn_17.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_16 = QPushButton(self.centralwidget)
        self.btn_16.setObjectName(u"btn_16")
        self.btn_16.setGeometry(QRect(410, 320, 61, 61))
        self.btn_16.setFont(font)
        self.btn_16.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_19 = QPushButton(self.centralwidget)
        self.btn_19.setObjectName(u"btn_19")
        self.btn_19.setGeometry(QRect(470, 320, 61, 61))
        self.btn_19.setFont(font)
        self.btn_19.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_20 = QPushButton(self.centralwidget)
        self.btn_20.setObjectName(u"btn_20")
        self.btn_20.setGeometry(QRect(470, 260, 61, 61))
        self.btn_20.setFont(font)
        self.btn_20.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_21 = QPushButton(self.centralwidget)
        self.btn_21.setObjectName(u"btn_21")
        self.btn_21.setGeometry(QRect(470, 200, 61, 61))
        self.btn_21.setFont(font)
        self.btn_21.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_22 = QPushButton(self.centralwidget)
        self.btn_22.setObjectName(u"btn_22")
        self.btn_22.setGeometry(QRect(530, 320, 61, 61))
        self.btn_22.setFont(font)
        self.btn_22.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_23 = QPushButton(self.centralwidget)
        self.btn_23.setObjectName(u"btn_23")
        self.btn_23.setGeometry(QRect(530, 260, 61, 61))
        self.btn_23.setFont(font)
        self.btn_23.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_24 = QPushButton(self.centralwidget)
        self.btn_24.setObjectName(u"btn_24")
        self.btn_24.setGeometry(QRect(530, 200, 61, 61))
        self.btn_24.setFont(font)
        self.btn_24.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_25 = QPushButton(self.centralwidget)
        self.btn_25.setObjectName(u"btn_25")
        self.btn_25.setGeometry(QRect(590, 320, 61, 61))
        self.btn_25.setFont(font)
        self.btn_25.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_26 = QPushButton(self.centralwidget)
        self.btn_26.setObjectName(u"btn_26")
        self.btn_26.setGeometry(QRect(590, 260, 61, 61))
        self.btn_26.setFont(font)
        self.btn_26.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_27 = QPushButton(self.centralwidget)
        self.btn_27.setObjectName(u"btn_27")
        self.btn_27.setGeometry(QRect(590, 200, 61, 61))
        self.btn_27.setFont(font)
        self.btn_27.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_28 = QPushButton(self.centralwidget)
        self.btn_28.setObjectName(u"btn_28")
        self.btn_28.setGeometry(QRect(650, 320, 61, 61))
        self.btn_28.setFont(font)
        self.btn_28.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_29 = QPushButton(self.centralwidget)
        self.btn_29.setObjectName(u"btn_29")
        self.btn_29.setGeometry(QRect(650, 260, 61, 61))
        self.btn_29.setFont(font)
        self.btn_29.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_30 = QPushButton(self.centralwidget)
        self.btn_30.setObjectName(u"btn_30")
        self.btn_30.setGeometry(QRect(650, 200, 61, 61))
        self.btn_30.setFont(font)
        self.btn_30.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_31 = QPushButton(self.centralwidget)
        self.btn_31.setObjectName(u"btn_31")
        self.btn_31.setGeometry(QRect(710, 320, 61, 61))
        self.btn_31.setFont(font)
        self.btn_31.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_32 = QPushButton(self.centralwidget)
        self.btn_32.setObjectName(u"btn_32")
        self.btn_32.setGeometry(QRect(710, 260, 61, 61))
        self.btn_32.setFont(font)
        self.btn_32.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_33 = QPushButton(self.centralwidget)
        self.btn_33.setObjectName(u"btn_33")
        self.btn_33.setGeometry(QRect(710, 200, 61, 61))
        self.btn_33.setFont(font)
        self.btn_33.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_34 = QPushButton(self.centralwidget)
        self.btn_34.setObjectName(u"btn_34")
        self.btn_34.setGeometry(QRect(770, 320, 61, 61))
        self.btn_34.setFont(font)
        self.btn_34.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_35 = QPushButton(self.centralwidget)
        self.btn_35.setObjectName(u"btn_35")
        self.btn_35.setGeometry(QRect(770, 260, 61, 61))
        self.btn_35.setFont(font)
        self.btn_35.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_36 = QPushButton(self.centralwidget)
        self.btn_36.setObjectName(u"btn_36")
        self.btn_36.setGeometry(QRect(770, 200, 61, 61))
        self.btn_36.setFont(font)
        self.btn_36.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_0 = QPushButton(self.centralwidget)
        self.btn_0.setObjectName(u"btn_0")
        self.btn_0.setGeometry(QRect(54, 200, 51, 181))
        font1 = QFont()
        font1.setPointSize(32)
        self.btn_0.setFont(font1)
        self.btn_0.setStyleSheet(u"background-color: rgb(0, 255, 0);")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Page 1", None))
        self.label.setText("")
        self.btn_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.btn_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.btn_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.btn_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.btn_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.btn_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.btn_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.btn_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.btn_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.btn_12.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.btn_11.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.btn_10.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.btn_15.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.btn_14.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.btn_13.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.btn_18.setText(QCoreApplication.translate("MainWindow", u"18", None))
        self.btn_17.setText(QCoreApplication.translate("MainWindow", u"17", None))
        self.btn_16.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.btn_19.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.btn_20.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.btn_21.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.btn_22.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.btn_23.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.btn_24.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.btn_25.setText(QCoreApplication.translate("MainWindow", u"25", None))
        self.btn_26.setText(QCoreApplication.translate("MainWindow", u"26", None))
        self.btn_27.setText(QCoreApplication.translate("MainWindow", u"27", None))
        self.btn_28.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.btn_29.setText(QCoreApplication.translate("MainWindow", u"29", None))
        self.btn_30.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.btn_31.setText(QCoreApplication.translate("MainWindow", u"31", None))
        self.btn_32.setText(QCoreApplication.translate("MainWindow", u"32", None))
        self.btn_33.setText(QCoreApplication.translate("MainWindow", u"33", None))
        self.btn_34.setText(QCoreApplication.translate("MainWindow", u"34", None))
        self.btn_35.setText(QCoreApplication.translate("MainWindow", u"35", None))
        self.btn_36.setText(QCoreApplication.translate("MainWindow", u"36", None))
        self.btn_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
    # retranslateUi

