# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'page_6.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1366, 786)
        MainWindow.setStyleSheet(u"background-color: rgb(170, 170, 255);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbl_roulette = QLabel(self.centralwidget)
        self.lbl_roulette.setObjectName(u"lbl_roulette")
        self.lbl_roulette.setGeometry(QRect(990, 30, 351, 701))
        font = QFont()
        font.setPointSize(25)
        self.lbl_roulette.setFont(font)
        self.lbl_roulette.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.btn_bet = QPushButton(self.centralwidget)
        self.btn_bet.setObjectName(u"btn_bet")
        self.btn_bet.setGeometry(QRect(50, 680, 131, 51))
        self.btn_bet.setFont(font)
        self.txt_bet = QLineEdit(self.centralwidget)
        self.txt_bet.setObjectName(u"txt_bet")
        self.txt_bet.setGeometry(QRect(40, 640, 161, 31))
        self.btn_allin = QPushButton(self.centralwidget)
        self.btn_allin.setObjectName(u"btn_allin")
        self.btn_allin.setGeometry(QRect(310, 620, 261, 121))
        font1 = QFont()
        font1.setPointSize(45)
        self.btn_allin.setFont(font1)
        self.btn_22 = QPushButton(self.centralwidget)
        self.btn_22.setObjectName(u"btn_22")
        self.btn_22.setGeometry(QRect(560, 330, 61, 61))
        font2 = QFont()
        font2.setPointSize(21)
        self.btn_22.setFont(font2)
        self.btn_22.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_33 = QPushButton(self.centralwidget)
        self.btn_33.setObjectName(u"btn_33")
        self.btn_33.setGeometry(QRect(740, 210, 61, 61))
        self.btn_33.setFont(font2)
        self.btn_33.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_7 = QPushButton(self.centralwidget)
        self.btn_7.setObjectName(u"btn_7")
        self.btn_7.setGeometry(QRect(260, 330, 61, 61))
        self.btn_7.setFont(font2)
        self.btn_7.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_15 = QPushButton(self.centralwidget)
        self.btn_15.setObjectName(u"btn_15")
        self.btn_15.setGeometry(QRect(380, 210, 61, 61))
        self.btn_15.setFont(font2)
        self.btn_15.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_35 = QPushButton(self.centralwidget)
        self.btn_35.setObjectName(u"btn_35")
        self.btn_35.setGeometry(QRect(800, 270, 61, 61))
        self.btn_35.setFont(font2)
        self.btn_35.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_18 = QPushButton(self.centralwidget)
        self.btn_18.setObjectName(u"btn_18")
        self.btn_18.setGeometry(QRect(440, 210, 61, 61))
        self.btn_18.setFont(font2)
        self.btn_18.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_31 = QPushButton(self.centralwidget)
        self.btn_31.setObjectName(u"btn_31")
        self.btn_31.setGeometry(QRect(740, 330, 61, 61))
        self.btn_31.setFont(font2)
        self.btn_31.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_1 = QPushButton(self.centralwidget)
        self.btn_1.setObjectName(u"btn_1")
        self.btn_1.setGeometry(QRect(140, 330, 61, 61))
        self.btn_1.setFont(font2)
        self.btn_1.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_23 = QPushButton(self.centralwidget)
        self.btn_23.setObjectName(u"btn_23")
        self.btn_23.setGeometry(QRect(560, 270, 61, 61))
        self.btn_23.setFont(font2)
        self.btn_23.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_29 = QPushButton(self.centralwidget)
        self.btn_29.setObjectName(u"btn_29")
        self.btn_29.setGeometry(QRect(680, 270, 61, 61))
        self.btn_29.setFont(font2)
        self.btn_29.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_11 = QPushButton(self.centralwidget)
        self.btn_11.setObjectName(u"btn_11")
        self.btn_11.setGeometry(QRect(320, 270, 61, 61))
        self.btn_11.setFont(font2)
        self.btn_11.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_14 = QPushButton(self.centralwidget)
        self.btn_14.setObjectName(u"btn_14")
        self.btn_14.setGeometry(QRect(380, 270, 61, 61))
        self.btn_14.setFont(font2)
        self.btn_14.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_12 = QPushButton(self.centralwidget)
        self.btn_12.setObjectName(u"btn_12")
        self.btn_12.setGeometry(QRect(320, 210, 61, 61))
        self.btn_12.setFont(font2)
        self.btn_12.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_27 = QPushButton(self.centralwidget)
        self.btn_27.setObjectName(u"btn_27")
        self.btn_27.setGeometry(QRect(620, 210, 61, 61))
        self.btn_27.setFont(font2)
        self.btn_27.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_30 = QPushButton(self.centralwidget)
        self.btn_30.setObjectName(u"btn_30")
        self.btn_30.setGeometry(QRect(680, 210, 61, 61))
        self.btn_30.setFont(font2)
        self.btn_30.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_36 = QPushButton(self.centralwidget)
        self.btn_36.setObjectName(u"btn_36")
        self.btn_36.setGeometry(QRect(800, 210, 61, 61))
        self.btn_36.setFont(font2)
        self.btn_36.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_25 = QPushButton(self.centralwidget)
        self.btn_25.setObjectName(u"btn_25")
        self.btn_25.setGeometry(QRect(620, 330, 61, 61))
        self.btn_25.setFont(font2)
        self.btn_25.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_19 = QPushButton(self.centralwidget)
        self.btn_19.setObjectName(u"btn_19")
        self.btn_19.setGeometry(QRect(500, 330, 61, 61))
        self.btn_19.setFont(font2)
        self.btn_19.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_4 = QPushButton(self.centralwidget)
        self.btn_4.setObjectName(u"btn_4")
        self.btn_4.setGeometry(QRect(200, 330, 61, 61))
        self.btn_4.setFont(font2)
        self.btn_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_17 = QPushButton(self.centralwidget)
        self.btn_17.setObjectName(u"btn_17")
        self.btn_17.setGeometry(QRect(440, 270, 61, 61))
        self.btn_17.setFont(font2)
        self.btn_17.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_13 = QPushButton(self.centralwidget)
        self.btn_13.setObjectName(u"btn_13")
        self.btn_13.setGeometry(QRect(380, 330, 61, 61))
        self.btn_13.setFont(font2)
        self.btn_13.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_3 = QPushButton(self.centralwidget)
        self.btn_3.setObjectName(u"btn_3")
        self.btn_3.setGeometry(QRect(140, 210, 61, 61))
        self.btn_3.setFont(font2)
        self.btn_3.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_10 = QPushButton(self.centralwidget)
        self.btn_10.setObjectName(u"btn_10")
        self.btn_10.setGeometry(QRect(320, 330, 61, 61))
        self.btn_10.setFont(font2)
        self.btn_10.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_28 = QPushButton(self.centralwidget)
        self.btn_28.setObjectName(u"btn_28")
        self.btn_28.setGeometry(QRect(680, 330, 61, 61))
        self.btn_28.setFont(font2)
        self.btn_28.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_21 = QPushButton(self.centralwidget)
        self.btn_21.setObjectName(u"btn_21")
        self.btn_21.setGeometry(QRect(500, 210, 61, 61))
        self.btn_21.setFont(font2)
        self.btn_21.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_26 = QPushButton(self.centralwidget)
        self.btn_26.setObjectName(u"btn_26")
        self.btn_26.setGeometry(QRect(620, 270, 61, 61))
        self.btn_26.setFont(font2)
        self.btn_26.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_20 = QPushButton(self.centralwidget)
        self.btn_20.setObjectName(u"btn_20")
        self.btn_20.setGeometry(QRect(500, 270, 61, 61))
        self.btn_20.setFont(font2)
        self.btn_20.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_32 = QPushButton(self.centralwidget)
        self.btn_32.setObjectName(u"btn_32")
        self.btn_32.setGeometry(QRect(740, 270, 61, 61))
        self.btn_32.setFont(font2)
        self.btn_32.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_24 = QPushButton(self.centralwidget)
        self.btn_24.setObjectName(u"btn_24")
        self.btn_24.setGeometry(QRect(560, 210, 61, 61))
        self.btn_24.setFont(font2)
        self.btn_24.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_9 = QPushButton(self.centralwidget)
        self.btn_9.setObjectName(u"btn_9")
        self.btn_9.setGeometry(QRect(260, 210, 61, 61))
        self.btn_9.setFont(font2)
        self.btn_9.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_5 = QPushButton(self.centralwidget)
        self.btn_5.setObjectName(u"btn_5")
        self.btn_5.setGeometry(QRect(200, 270, 61, 61))
        self.btn_5.setFont(font2)
        self.btn_5.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.btn_6 = QPushButton(self.centralwidget)
        self.btn_6.setObjectName(u"btn_6")
        self.btn_6.setGeometry(QRect(200, 210, 61, 61))
        self.btn_6.setFont(font2)
        self.btn_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_16 = QPushButton(self.centralwidget)
        self.btn_16.setObjectName(u"btn_16")
        self.btn_16.setGeometry(QRect(440, 330, 61, 61))
        self.btn_16.setFont(font2)
        self.btn_16.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_2 = QPushButton(self.centralwidget)
        self.btn_2.setObjectName(u"btn_2")
        self.btn_2.setGeometry(QRect(140, 270, 61, 61))
        self.btn_2.setFont(font2)
        self.btn_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_0 = QPushButton(self.centralwidget)
        self.btn_0.setObjectName(u"btn_0")
        self.btn_0.setGeometry(QRect(84, 210, 51, 181))
        font3 = QFont()
        font3.setPointSize(32)
        self.btn_0.setFont(font3)
        self.btn_0.setStyleSheet(u"background-color: rgb(0, 255, 0);")
        self.btn_34 = QPushButton(self.centralwidget)
        self.btn_34.setObjectName(u"btn_34")
        self.btn_34.setGeometry(QRect(800, 330, 61, 61))
        self.btn_34.setFont(font2)
        self.btn_34.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btn_8 = QPushButton(self.centralwidget)
        self.btn_8.setObjectName(u"btn_8")
        self.btn_8.setGeometry(QRect(260, 270, 61, 61))
        self.btn_8.setFont(font2)
        self.btn_8.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.lbl_balance = QLabel(self.centralwidget)
        self.lbl_balance.setObjectName(u"lbl_balance")
        self.lbl_balance.setGeometry(QRect(20, 20, 441, 71))
        font4 = QFont()
        font4.setPointSize(23)
        self.lbl_balance.setFont(font4)
        self.lbl_error = QLabel(self.centralwidget)
        self.lbl_error.setObjectName(u"lbl_error")
        self.lbl_error.setGeometry(QRect(90, 440, 621, 121))
        font5 = QFont()
        font5.setPointSize(35)
        self.lbl_error.setFont(font5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_bet.clicked.connect(MainWindow.btn_bet_a)
        self.btn_allin.clicked.connect(MainWindow.btn_allin_a)
        self.btn_0.clicked.connect(MainWindow.betting)
        self.btn_1.clicked.connect(MainWindow.betting)
        self.btn_2.clicked.connect(MainWindow.betting)
        self.btn_3.clicked.connect(MainWindow.betting)
        self.btn_4.clicked.connect(MainWindow.betting)
        self.btn_5.clicked.connect(MainWindow.betting)
        self.btn_7.clicked.connect(MainWindow.betting)
        self.btn_6.clicked.connect(MainWindow.betting)
        self.btn_8.clicked.connect(MainWindow.betting)
        self.btn_9.clicked.connect(MainWindow.betting)
        self.btn_10.clicked.connect(MainWindow.betting)
        self.btn_11.clicked.connect(MainWindow.betting)
        self.btn_11.clicked.connect(MainWindow.betting)
        self.btn_12.clicked.connect(MainWindow.betting)
        self.btn_13.clicked.connect(MainWindow.betting)
        self.btn_14.clicked.connect(MainWindow.betting)
        self.btn_15.clicked.connect(MainWindow.betting)
        self.btn_16.clicked.connect(MainWindow.betting)
        self.btn_17.clicked.connect(MainWindow.betting)
        self.btn_18.clicked.connect(MainWindow.betting)
        self.btn_19.clicked.connect(MainWindow.betting)
        self.btn_20.clicked.connect(MainWindow.betting)
        self.btn_21.clicked.connect(MainWindow.betting)
        self.btn_22.clicked.connect(MainWindow.betting)
        self.btn_23.clicked.connect(MainWindow.betting)
        self.btn_24.clicked.connect(MainWindow.betting)
        self.btn_25.clicked.connect(MainWindow.betting)
        self.btn_26.clicked.connect(MainWindow.betting)
        self.btn_27.clicked.connect(MainWindow.betting)
        self.btn_28.clicked.connect(MainWindow.betting)
        self.btn_29.clicked.connect(MainWindow.betting)
        self.btn_30.clicked.connect(MainWindow.betting)
        self.btn_31.clicked.connect(MainWindow.betting)
        self.btn_32.clicked.connect(MainWindow.betting)
        self.btn_33.clicked.connect(MainWindow.betting)
        self.btn_34.clicked.connect(MainWindow.betting)
        self.btn_35.clicked.connect(MainWindow.betting)
        self.btn_36.clicked.connect(MainWindow.betting)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Page 1", None))
        self.lbl_roulette.setText("")
        self.btn_bet.setText(QCoreApplication.translate("MainWindow", u"BET", None))
        self.btn_allin.setText(QCoreApplication.translate("MainWindow", u"ALL IN!!", None))
        self.btn_22.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.btn_33.setText(QCoreApplication.translate("MainWindow", u"33", None))
        self.btn_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.btn_15.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.btn_35.setText(QCoreApplication.translate("MainWindow", u"35", None))
        self.btn_18.setText(QCoreApplication.translate("MainWindow", u"18", None))
        self.btn_31.setText(QCoreApplication.translate("MainWindow", u"31", None))
        self.btn_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.btn_23.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.btn_29.setText(QCoreApplication.translate("MainWindow", u"29", None))
        self.btn_11.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.btn_14.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.btn_12.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.btn_27.setText(QCoreApplication.translate("MainWindow", u"27", None))
        self.btn_30.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.btn_36.setText(QCoreApplication.translate("MainWindow", u"36", None))
        self.btn_25.setText(QCoreApplication.translate("MainWindow", u"25", None))
        self.btn_19.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.btn_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.btn_17.setText(QCoreApplication.translate("MainWindow", u"17", None))
        self.btn_13.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.btn_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.btn_10.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.btn_28.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.btn_21.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.btn_26.setText(QCoreApplication.translate("MainWindow", u"26", None))
        self.btn_20.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.btn_32.setText(QCoreApplication.translate("MainWindow", u"32", None))
        self.btn_24.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.btn_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.btn_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.btn_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.btn_16.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.btn_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.btn_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.btn_34.setText(QCoreApplication.translate("MainWindow", u"34", None))
        self.btn_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.lbl_balance.setText(QCoreApplication.translate("MainWindow", u"BALANCE:", None))
        self.lbl_error.setText("")
    # retranslateUi

